clarify expectations, desired plots embedded as images
learn-co-curriculum/dsc-more-practice-with-matplotlib-lab pull request #3
Opened 2021-01-07 15:54 UTC by hoffm386

1. Adds `# Your code here` and clarifies instructions throughout
2. Embeds the desired graph images in the notebook, so students can run the cell as many times as they want and check it against the specified image. Previously the first time they would run the cell for each exercise, the specified graph would disappear
3. Some solution code improvements (using NumPy broadcasting instead of list comprehension, matching variable names specified in instructions, adding comments)
4. Grammar fixes

2021-01-21 20:06 UTC, Ben-Oren requested changes

2021-01-21 20:06 UTC, Ben-Oren commented on index.ipynb
> +    "![two subplots](graph_images/subplots_left_right.png)"
The image of the graph has the y-axis label of the second graph "running into" the visual of the first graph

Easiest way I know to fix this is to use `.tight_layout()` as the last line of the viz.  (Note that if it's not the last line, it won't work.)

Could put the offending y-axis label on the right hand side of the graph instead of the left side, but that would require further elaboration to students and make an already-long prework session longer.

Plus `.tight_layout()` is useful enough to be worthwhile to introduce.  

So:
- Include the student-facing note below at this spot in the book 
- Include `.tight_layout` in the solution code and save figure (outlined in an additional note below at line 365)
- Re-run the code with the changed figure to save it
- Re-run the instruction cell importing the figure so that the just-saved figure shows up
- Delete the `.savefig`  code used to generate the new figure
- Re-run the solution cell code generating the graph so that the graph will be visualized in the book

Note to include at this spot in the book:

**Note**: if you create a figure that looks like the above except the y-axis label for the second graph is "running into" the second graph, make the last line of your code your figure object followed by `.tight_layout();`.  This will try to automatically space graphs so that labels are not overlapping other objects.

2021-01-21 20:06 UTC, Ben-Oren commented on index.ipynb
> +    "ax2.set_title ('Right Plot');"
In order to use `.tight_layout()` to fix the second graph's y-axis label running into the first graph as outlined in the note at line 322:

- Remove the semicolon from line 365
- Insert the following at line 366 (after `ax2.set_title ('Right Plot')`):
   - `new_figure.tight_layout();`
   - `new_figure.savefig('graph_images/subplots_left_right.png')`
- Re-run the instructions cell above in order to re-load the figure that was just saved
- Delete the now-superfluous `new_figure.savefig('graph_images/subplots_left_right.png')` line
- Re-run the solution cell so that it will generate a graph when viewed

2021-01-22 18:11 UTC, hoffm386 commented on index.ipynb
> +    "![two subplots](graph_images/subplots_left_right.png)"
The idea here (as well as in the original version of this lab) was that this plot is intentionally kind of messed-up looking, then the next question asks them to make some changes to make it look better. So, I'm planning to leave this as-is, but introduce `.tight_layout` as an alternative option later

2021-01-22 20:12 UTC, Ben-Oren commented on index.ipynb
> +    "![two subplots](graph_images/subplots_left_right.png)"
Ahhh, gotchya.  Cool idea.

2021-01-22 20:13 UTC, Ben-Oren approved these changes

2021-01-22 20:37 UTC, merged